Repository usdigitalresponse/cpf-reporter, pull requests merged in 2024-07, with the labels that each got.

#350 Limit file size upload
  web/src/components/Upload/UploadForm/UploadForm.tsx
Labels: javascript

#353 Expose subrecipients on ValidationResults in workbook_validator
  python/src/lib/workbook_validator.py
  python/tests/src/lib/test_workbook_validator.py
Labels: python

#354 Fix value unpacking in validate_workbook
  python/src/functions/validate_workbook.py
Labels: bug, python

#355 Make subrecipients into JSON explicitly
  python/src/lib/workbook_validator.py
  python/src/schemas/schema_V2024_04_01.py
  python/src/schemas/schema_V2024_05_24.py
Labels: python

#358 Schema tweaks for Subrecipients and SubrecipientUploads
  api/db/migrations/20240710175847_subrecipient_changes/migration.sql
  api/db/schema.prisma
  api/src/graphql/subrecipientUploads.sdl.ts
  api/src/graphql/subrecipients.sdl.ts
  api/src/graphql/uploads.sdl.ts
  api/src/services/subrecipientUploads/subrecipientUploads.scenarios.ts
  api/src/services/subrecipientUploads/subrecipientUploads.test.ts
  api/src/services/subrecipientUploads/subrecipientUploads.ts
  api/src/services/subrecipients/subrecipients.scenarios.ts
  api/src/services/subrecipients/subrecipients.test.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: javascript, database

#363 Expose version string on return payload for validator
  api/src/functions/processValidationJson/processValidationJson.test.ts
  python/src/functions/validate_workbook.py
  python/src/lib/workbook_validator.py
  python/tests/src/lib/test_workbook_validator.py
Labels: javascript, python

#364 Use real version passed in to save `SubrecipientUpload`
  api/src/functions/processValidationJson/processValidationJson.ts
Labels: javascript

#365 Save subrecipient information to S3
  api/src/functions/processValidationJson/processValidationJson.ts
Labels: javascript

#366 Adding skeleton lambda for subrecipient file gen
  .vscode/settings.json
  python/src/functions/subrecipient_treasury_report_gen.py
  terraform/functions.tf
Labels: terraform, infra, python

#352 tz/298/uploads-by-expenditure-category
  api/src/lib/aws.test.ts
  api/src/lib/aws.ts
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
Labels: javascript

#338 Generate treasury report for Projects 1A, 1B, 1C
  python/src/functions/generate_treasury_report.py
  python/src/lib/workbook_validator.py
  python/src/schemas/project_types.py
  python/src/schemas/schema_V2024_05_24.py
  python/tests/conftest.py
  python/tests/data/treasury/sample_1A_input_pass.xlsm
  python/tests/data/treasury/sample_1A_output.xlsx
  python/tests/data/treasury/sample_1B_input_pass.xlsm
  python/tests/data/treasury/sample_1B_output.xlsx
  python/tests/data/treasury/sample_1C_input_pass.xlsm
  python/tests/data/treasury/sample_1C_output.xlsx
  python/tests/data/treasury/~$sample_1C_input_pass.xlsm
  python/tests/src/lib/test_treasury_report_1A.py
  python/tests/src/lib/test_treasury_report_1B.py
  python/tests/src/lib/test_treasury_report_1C.py
  scripts/seed.ts
  terraform/functions.tf
Labels: enhancement, javascript, terraform, infra, python

#369 CPF-296 Treasury Report GraphQL Mutation
  api/src/graphql/uploads.sdl.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  api/types/graphql.d.ts
  docker-compose.dev.yml
Labels: enhancement, javascript, infra

#372 CPF-295 Trigger sendTreasuryReport mutation from the Uploads page
  web/src/pages/Upload/UploadsPage/UploadsPage.tsx
Labels: enhancement, javascript

#370 feat: FE and graphql scaffolding for manual treasury report generation
  api/src/graphql/organizations.sdl.ts
  api/src/lib/aws.ts
  api/src/services/organizations/organizations.test.ts
  api/src/services/organizations/organizations.ts
  api/types/graphql.d.ts
  web/src/Routes.tsx
  web/src/components/Navigation/Navigation.tsx
  web/src/components/TreasuryGeneration/DownloadTreasuryFiles/DownloadTreasuryFiles.tsx
  web/src/components/TreasuryGeneration/NewTreasuryGeneration/NewTreasuryGeneration.tsx
  web/src/components/TreasuryGeneration/NewTreasuryGenerationForm/NewTreasuryGenerationForm.tsx
  web/src/pages/ToolsPage/TreasuryReportGenerationPage/TreasuryReportGenerationPage.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript

#373 Remove organization as a field on reporting period
  api/db/migrations/20240727060426_/migration.sql
  api/db/schema.prisma
  api/src/functions/processValidationJson/processValidationJson.scenarios.ts
  api/src/graphql/organizations.sdl.ts
  api/src/graphql/reportingPeriods.sdl.ts
  api/src/services/organizations/organizations.scenarios.ts
  api/src/services/organizations/organizations.test.ts
  api/src/services/projects/projects.scenarios.ts
  api/src/services/reportingPeriods/reportingPeriods.scenarios.ts
  api/src/services/reportingPeriods/reportingPeriods.test.ts
  api/src/services/reportingPeriods/reportingPeriods.ts
  api/src/services/subrecipientUploads/subrecipientUploads.scenarios.ts
  api/src/services/uploadValidations/uploadValidations.scenarios.ts
  api/src/services/uploads/uploads.scenarios.ts
  web/src/components/Organization/OrganizationPickListsCell/OrganizationPickListsCell.mock.ts
  web/src/components/Organization/OrganizationPickListsCell/OrganizationPickListsCell.tsx
  web/src/components/ReportingPeriod/EditReportingPeriodCell/EditReportingPeriodCell.tsx
  web/src/components/ReportingPeriod/ReportingPeriod/ReportingPeriod.tsx
  web/src/components/ReportingPeriod/ReportingPeriodCell/ReportingPeriodCell.tsx
  web/src/components/ReportingPeriod/ReportingPeriodForm/ReportingPeriodForm.tsx
  web/src/components/ReportingPeriod/ReportingPeriods/ReportingPeriods.tsx
  web/src/components/ReportingPeriod/ReportingPeriodsCell/ReportingPeriodsCell.tsx
Labels: javascript, database

#371 chore: ensure graphql lambda function has the correct IAM permissions
  .env.defaults
  python/src/functions/generate_treasury_report.py
  terraform/functions.tf
  terraform/treasury_generation_lambda_functions.tf
  terraform/treasury_generation_step_function.tf
Labels: javascript, terraform, infra, python
