Repository usdigitalresponse/cpf-reporter, pull requests merged in 2024-10, with the labels that each got.

#457 fix: add report.zip in the correct s3 path
  python/src/functions/create_archive.py
  python/tests/src/lib/test_create_archive.py
Labels: bug, python

#458 fix: ensure that json files are loaded in text-mode
  python/src/functions/generate_treasury_report.py
  python/src/functions/subrecipient_treasury_report_gen.py
Labels: bug, python

#459 chore: add success email as last step of treasury generation
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  terraform/treasury_generation_step_function.tf
Labels: javascript, terraform, infra

#461 fix: ensure encryption-config is passed to s3 upload-file
  python/src/functions/create_archive.py
  python/tests/src/lib/test_create_archive.py
Labels: bug, python

#462 Fix - ensure the treasury generation step functions an invoke send-email lambda
  python/src/functions/generate_presigned_url_and_send_email.py
  terraform/treasury_generation_lambda_functions.tf
  terraform/treasury_generation_step_function.tf
Labels: bug, terraform, infra, python

#463 fix: ensure handler is correctly defined in lambda function
  terraform/treasury_generation_lambda_functions.tf
Labels: bug, terraform, infra

#467 chore: enable send-treasury-report and subrecipients for organization admins
  web/src/Routes.tsx
  web/src/pages/Upload/UploadsPage/UploadsPage.tsx
Labels: javascript

#468 CPF-452 Fix transaction timeout
  api/src/services/reportingPeriods/reportingPeriods.ts
Labels: bug, javascript

#469 fix: ensure subrecipients option shows up in nav-bar
  web/src/components/Navigation/Navigation.tsx
Labels: bug, javascript

#473 Feat: Reporting Period ID column
  api/setup-jest.ts
  web/src/components/ReportingPeriod/ReportingPeriods/columns.tsx
Labels: enhancement, javascript

#476 Bug: flaky test 460
  api/src/graphql/users.sdl.ts
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/users/users.test.ts
  api/src/services/users/users.ts
Labels: bug, javascript

#477 Speedups and enhancements for GitHub Actions CI workflows
  .github/workflows/aws-auth.yml
  .github/workflows/build.yml
  .github/workflows/code-scanning.yml
  .github/workflows/deploy-production.yml
  .github/workflows/publish-qa-results.yml
  .github/workflows/publish-terraform-plan.yml
  .github/workflows/qa.yml
  .github/workflows/release-drafter.yml
  .github/workflows/terraform-apply.yml
  .github/workflows/terraform-plan.yml
  .github/workflows/validate-deployment.yml
  .yarnrc.yml
  api/jest.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: github, javascript, dependencies

#486 chore: hide invalidate button from all users except usdr-admins
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
Labels: javascript

#484 chore: add missing unit tests for getValidUploads function
  api/src/functions/processValidationJson/processValidationJson.ts
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
Labels: javascript

#487 Chore: add confirmation toast for treasury email
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  web/src/pages/Upload/UploadsPage/UploadsPage.tsx
Labels: enhancement, javascript

#490 fix: ensure treasury generation payload has information for all projects
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
Labels: bug, javascript

#498 feat: add front end button to upload subrecipients
  api/src/graphql/subrecipients.sdl.ts
  api/src/services/subrecipients/subrecipients.ts
  web/src/components/TreasuryGeneration/DownloadTreasuryFiles/DownloadTreasuryFiles.tsx
Labels: enhancement, javascript

#502 refactor: logic flow for saving and maintaining subrecipient state
  api/src/functions/processValidationJson/processValidationJson.ts
Labels: javascript
