Repository usdigitalresponse/cpf-reporter, pull requests merged in 2024-03, with the labels that each got.

#118 CPF-116 Add passageId field to User model
  api/db/migrations/20240301190538_add_passage_id/migration.sql
  api/db/schema.prisma
Labels: enhancement, javascript, database

#108 Adds ability for developers to authenticate users in the local environment
  .env.defaults
  api/src/lib/auth.ts
  scripts/seed.ts
  web/package.json
  web/src/auth.ts
  web/src/auth/localAuth.ts
  web/src/lib/seeds.ts
  web/src/pages/LoginPage/LoginPage.test.tsx
  web/src/pages/LoginPage/LoginPage.tsx
  yarn.lock
Labels: javascript, terraform, infra, dependencies

#112 CPF-101 Update createUser() mutation resolver
  .vscode/settings.json
  api/src/graphql/users.sdl.ts
  api/src/lib/auth.ts
  api/src/services/users/users.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: enhancement, javascript

#128 Implement access controls for user queries
  api/src/services/users/users.scenarios.ts
  api/src/services/users/users.test.ts
  api/src/services/users/users.ts
Labels: javascript

#129 CPF-117 Create and delete Passage user
  api/package.json
  api/src/lib/auth.ts
  api/src/services/passage/passage.test.ts
  api/src/services/passage/passage.ts
  scripts/passageAuth.ts
  web/types/graphql.d.ts
  yarn.lock
Labels: enhancement, javascript, dependencies

#134 120 passage authentication add configuration parameters for the front end
  terraform/staging.tfvars
  terraform/tpl/deploy-config.js
  terraform/variables.tf
  terraform/web.tf
Labels: javascript, terraform, infra

#131 Update user changes
  api/src/graphql/users.sdl.ts
  api/src/services/users/users.scenarios.ts
  api/src/services/users/users.test.ts
  api/src/services/users/users.ts
Labels: javascript

#146 CPF-137 Implement latestValidation
  api/db/migrations/20240326015020_upload_validation_cascade_delete/migration.sql
  api/db/schema.prisma
  api/src/graphql/uploads.sdl.ts
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  api/types/graphql.d.ts
  web/src/components/Upload/Uploads/Uploads.tsx
  web/src/components/Upload/Uploads/columns.tsx
  web/src/components/Upload/UploadsCell/UploadsCell.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript, database

#147 UploadValidation database changes
  api/db/migrations/20240326182611_upload_validation_changes/migration.sql
  api/db/schema.prisma
  api/src/graphql/uploadValidations.sdl.ts
  api/src/services/uploadValidations/uploadValidations.scenarios.ts
  api/src/services/uploadValidations/uploadValidations.ts
  api/src/services/uploads/uploads.scenarios.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: javascript, database

#141 fix: rendering issues due to user permissions
  api/src/lib/auth.ts
  web/src/auth.ts
Labels: bug, javascript

#149 CPF-137 remove validatedAt and invalidatedAt, use passed instead
  web/src/components/Upload/Uploads/columns.tsx
  web/src/components/Upload/UploadsCell/UploadsCell.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript

#150 Remove invalidated at and validated at fields
  api/db/migrations/20240328204626_remove_validated_and_invalidated_at_fields/migration.sql
  api/db/schema.prisma
  api/src/graphql/uploadValidations.sdl.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: javascript, database

#153 Remove notes field
  api/db/migrations/20240329180952_remove_notes_from_uploads/migration.sql
  api/db/schema.prisma
  api/src/graphql/uploads.sdl.ts
  api/src/lib/persist-upload.js
  api/types/graphql.d.ts
  web/src/components/Upload/UploadForm/UploadForm.tsx
  web/types/graphql.d.ts
Labels: javascript, database
