Repository usdigitalresponse/cpf-reporter, pull requests merged in 2024-05, with the labels that each got.

#237 Release drafter updates
  .github/release-drafter.yml
Labels: enhancement, github

#240 Configure Terraform for Production environment
  .github/workflows/terraform-plan.yml
  terraform/production.s3.tfbackend
  terraform/production.tfvars
Labels: enhancement, github, terraform, infra

#241 CPF-122 Add Passage login element
  web/src/pages/LoginPage/LoginPage.tsx
  web/types/passage.d.ts
Labels: enhancement, javascript

#242 Fix #240 environment settings & add `tf-summarize`
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/publish-terraform-plan.yml
  .github/workflows/terraform-plan.yml
Labels: bug, github

#244 chore: enable passage in staging
  terraform/api_gateway.tf
  terraform/staging.tfvars
  terraform/variables.tf
Labels: terraform, infra

#250 Fix `tar` command for building release artifact for web
  .github/workflows/deploy-production.yml
Labels: bug, github

#251 Fix authorizer config for APIGW integration routes & make Passage required
  terraform/api_gateway.tf
  terraform/functions.tf
  terraform/production.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
  terraform/web.tf
Labels: bug, terraform, infra

#246 Upgrade RedwoodJS to 7.4.3
  .nvmrc
  Dockerfile
  api/package.json
  api/server.config.js
  api/src/server.ts
  api/types/graphql.d.ts
  docs/README.md
  package.json
  terraform/production.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
  web/package.json
  web/src/pages/ReportingPeriod/ReportingPeriodsPage/ReportingPeriodsPage.test.tsx
  web/src/pages/UploadTemplatePage/UploadTemplatePage.test.tsx
  web/tsconfig.json
  web/types/graphql.d.ts
  yarn.lock
Labels: documentation, enhancement, javascript, terraform, infra, dependencies

#254 fix: prisma openssl version with node 20 upgrade
  api/db/schema.prisma
Labels: bug, javascript, database

#255 chore: add logging around login failures
  api/src/lib/auth.ts
Labels: javascript

#256 Add Passage app ID for Production
  terraform/production.tfvars
Labels: bug, terraform, infra

#257 chore: add logging to debug passage
  api/src/lib/auth.ts
Labels: javascript

#258 fix: logging custom objects
  api/src/lib/auth.ts
Labels: bug, javascript

#259 chore: update payload version to 2.0
  terraform/api_gateway.tf
Labels: terraform, infra

#260 Revert "chore: update payload version to 2.0"
  terraform/api_gateway.tf
Labels: bug, terraform, infra, skip-changelog

#261 fix: update passage code to use api gateway payload format v1.0
  api/src/lib/auth.test.ts
  api/src/lib/auth.ts
Labels: bug, javascript

#263 Mark unrequired fields as Optionals in schema
  python/src/schemas/latest/schema.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: python

#264 chore: adds logging around passage permissions failures
  api/src/lib/auth.ts
Labels: javascript

#265 chore: add logging around the catch-block
  api/src/lib/auth.ts
Labels: javascript

#266 chore: explicitly log error with user-auth
  api/src/lib/auth.ts
Labels: javascript

#268 fix: ensure db is always a prismaclient
  api/src/lib/auth.ts
  api/src/lib/db.ts
Labels: bug, javascript

#231 Add ValidationRules to UploadValidation
  api/db/migrations/20240426212009_add_validation_rules_to_upload_validations/migration.sql
  api/db/schema.prisma
  api/src/graphql/uploadValidations.sdl.ts
  api/src/graphql/validationRuleses.sdl.ts
  api/src/services/validationRuleses/validationRuleses.scenarios.ts
  api/src/services/validationRuleses/validationRuleses.test.ts
  api/src/services/validationRuleses/validationRuleses.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: javascript, database

#275 Create global setup for Jest tests so db is present
  api/jest.config.js
  api/setup-jest.ts
  api/src/lib/auth.test.ts
  api/src/lib/db.ts
Labels: javascript

#273 fix: ensure all graphql requests start with initializing the database
  api/jest.config.js
  api/setup-jest.ts
  api/src/functions/graphql.ts
  api/src/functions/processValidationJson/processValidationJson.ts
  api/src/lib/auth.test.ts
  api/src/lib/db.ts
Labels: bug, javascript

#277 Workbook comparator
  .gitattributes
  python/src/lib/output_template_comparator.py
  python/tests/conftest.py
  python/tests/data/sample_template.xlsx
  python/tests/data/sample_template_2.xlsx
  python/tests/src/lib/test_output_template_comparator.py
Labels: enhancement, github, python

#280 Reporting periods schema changes
  api/db/migrations/20240521213042_reporting_period_changes/migration.sql
  api/db/schema.prisma
  api/src/graphql/reportingPeriods.sdl.ts
  api/src/graphql/users.sdl.ts
  api/src/graphql/validationRuleses.sdl.ts
  api/src/services/reportingPeriods/reportingPeriods.test.ts
  api/src/services/reportingPeriods/reportingPeriods.ts
  api/src/services/users/users.ts
  api/src/services/validationRuleses/validationRuleses.ts
  api/types/graphql.d.ts
  scripts/seed.ts
  web/src/components/ReportingPeriod/EditReportingPeriodCell/EditReportingPeriodCell.tsx
  web/src/components/ReportingPeriod/ReportingPeriod/ReportingPeriod.tsx
  web/src/components/ReportingPeriod/ReportingPeriodCell/ReportingPeriodCell.tsx
  web/src/components/ReportingPeriod/ReportingPeriodForm/ReportingPeriodForm.tsx
  web/src/components/ReportingPeriod/ReportingPeriods/ReportingPeriods.tsx
  web/src/components/ReportingPeriod/ReportingPeriodsCell/ReportingPeriodsCell.tsx
  web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
  web/types/graphql.d.ts
Labels: javascript, database

#279 Adds a script to create new expenditure-categories, templates, reporting periods, organizations, agencies, and users
  api/db/migrations/20240522032556_make_org_id_optional/migration.sql
  api/db/schema.prisma
  api/src/lib/constants.ts
  api/src/services/agencies/agencies.scenarios.ts
  api/src/services/agencies/agencies.test.ts
  api/src/services/agencies/agencies.ts
  api/src/services/expenditureCategories/expenditureCategories.test.ts
  api/src/services/expenditureCategories/expenditureCategories.ts
  api/src/services/inputTemplates/inputTemplates.test.ts
  api/src/services/inputTemplates/inputTemplates.ts
  api/src/services/organizations/organizations.scenarios.ts
  api/src/services/organizations/organizations.test.ts
  api/src/services/organizations/organizations.ts
  api/src/services/outputTemplates/outputTemplates.test.ts
  api/src/services/outputTemplates/outputTemplates.ts
  api/src/services/passage/passage.test.ts
  api/src/services/passage/passage.ts
  api/src/services/reportingPeriods/reportingPeriods.scenarios.ts
  api/src/services/reportingPeriods/reportingPeriods.test.ts
  api/src/services/reportingPeriods/reportingPeriods.ts
  api/src/services/users/users.test.ts
  api/src/services/users/users.ts
  scripts/onboardOrganization.ts
  web/src/components/Organization/OrganizationPickListsCell/OrganizationPickListsCell.tsx
  web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
Labels: javascript, database

#269 Enable docker for local development
  Dockerfile
  README.md
  docker-compose.dev.yml
  redwood.toml
  web/public/deploy-config.js
Labels: documentation, enhancement, javascript, infra

#276 add: update error messages and pydantic validators
  python/src/lib/workbook_validator.py
  python/src/schemas/latest/schema.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: documentation, enhancement, javascript, infra, python

#283 chore: strip whitespaces for validation
  python/src/lib/workbook_validator.py
  python/src/schemas/latest/schema.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: enhancement, python

#278 Document architecture in README
  README.md
  docs/component-level-architecture.png
Labels: documentation

#293 Adding versioning & new fields to python schema
  docs/python-schema.md
  python/src/functions/validate_workbook.py
  python/src/lib/workbook_validator.py
  python/src/schemas/latest/__init__.py
  python/src/schemas/project_types.py
  python/src/schemas/schema_V2024_04_01.py
  python/src/schemas/schema_V2024_05_24.py
  python/src/schemas/schema_versions.py
  python/tests/conftest.py
  python/tests/data/sample_valid_V2024_05_24.xlsm
  python/tests/src/lib/test_workbook_validator.py
Labels: documentation, python
