Repository usdigitalresponse/cpf-reporter, pull requests merged in 2024-06, with the labels that each got.

#299 Add current_reporting_period_id to organization preferences where it doesn't exist
  api/db/migrations/20240603182838_populate_organization_preferences/migration.sql
Labels: javascript, database

#309 CPF-289 Fetch all uploads under the same agency for "organization_staff" users
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
Labels: enhancement, javascript

#307 Adjust error messages
  python/src/lib/workbook_validator.py
  python/src/schemas/schema_V2024_04_01.py
  python/src/schemas/schema_V2024_05_24.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: bug, python

#300 Add subrecipient validation
  python/src/lib/workbook_validator.py
  python/src/schemas/schema_V2024_04_01.py
  python/src/schemas/schema_V2024_05_24.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: python

#314 chore: Update error descriptions
  python/src/lib/workbook_validator.py
  python/tests/src/lib/test_workbook_validator.py
Labels: bug, python

#312 CPF-302 update validation result text
  web/src/components/Upload/UploadValidationStatus/UploadValidationStatus.tsx
  web/src/components/Upload/Uploads/columns.tsx
Labels: enhancement, javascript

#323 Add output_columns to json_schema_extra for SubrecipientRow fields
  python/src/schemas/schema_V2024_05_24.py
Labels: python

#330 working on schema
  api/db/migrations/20240613203006_subrecipient_schema_updates/migration.sql
  api/db/schema.prisma
  api/src/graphql/subrecipientUploads.sdl.ts
  api/src/graphql/subrecipients.sdl.ts
  api/src/services/subrecipientUploads/subrecipientUploads.scenarios.ts
  api/src/services/subrecipientUploads/subrecipientUploads.test.ts
  api/src/services/subrecipientUploads/subrecipientUploads.ts
  api/src/services/subrecipients/subrecipients.scenarios.ts
  api/src/services/subrecipients/subrecipients.test.ts
  api/src/services/subrecipients/subrecipients.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: javascript, database

#336 chore: read more columns in for project sheet
  python/src/lib/workbook_validator.py
Labels: bug, python

#335 CPF-313 Conditional agency dropdown
  api/src/graphql/agencies.sdl.ts
  api/src/services/agencies/agencies.ts
  api/types/graphql.d.ts
  web/src/components/Organization/OrganizationPickListsCell/OrganizationPickListsCell.tsx
  web/src/components/Upload/NewUpload/NewUpload.tsx
  web/src/components/Upload/UploadForm/UploadForm.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript

#308 Enforce linter checks in CI
  .github/workflows/qa.yml
  .vscode/extensions.json
  .vscode/settings.json
  python/src/functions/validate_workbook.py
  python/src/lib/output_template_comparator.py
  python/src/lib/workbook_validator.py
  python/src/schemas/project_types.py
  python/src/schemas/schema_V2024_04_01.py
  python/src/schemas/schema_V2024_05_24.py
  python/src/schemas/schema_versions.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
  scripts/onboardOrganization.ts
  scripts/passageAuth.ts
Labels: bug, github, javascript, python

#337 CPF-313-2 conditional agency dropdown, refactor PR
  api/src/services/agencies/agencies.ts
Labels: enhancement, javascript

#342 chore: update validation for version
  python/src/lib/workbook_validator.py
  python/src/schemas/schema_versions.py
  python/tests/conftest.py
  python/tests/data/sample_old_version.xlsm
  python/tests/src/lib/test_workbook_validator.py
Labels: python

#331 chore: ensure generated graphql type-files are not committed
  .gitignore
Labels: github

#343 Provide DB client to validator function when creating user
  api/src/services/users/users.ts
Labels: bug, javascript

#344 Address warning messages
  api/src/functions/processValidationJson/processValidationJson.test.ts
  api/src/functions/processValidationJson/processValidationJson.ts
  python/src/lib/workbook_validator.py
  web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.tsx
Labels: javascript, python

#340 tz/297/aws step functions
  api/package.json
  api/src/lib/aws.ts
  localstack/docker-compose.yml
  localstack/entrypoint/init-aws.sh
  scripts/awsTest.ts
  scripts/sample_lambda.js
  scripts/sample_lambda.py
  yarn.lock
Labels: javascript, infra, dependencies

#346 feat: add ability to delete and reset testfiles
  api/src/lib/aws.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  scripts/deleteTestFiles.ts
Labels: enhancement, javascript

#347 fix: ensure terraform has the appropriate permissions
  terraform/ecs_redwood_console.tf
Labels: bug, javascript, terraform, infra

#349 fix: remove ability to delete from s3 due to permissions issue
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
Labels: bug, javascript
