Repository usdigitalresponse/cpf-reporter, pull requests merged in 2024-04, with the labels that each got.

#151 Upload Results Table component
  web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.stories.tsx
  web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.test.tsx
  web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.tsx
Labels: javascript

#154 fix: remove expenditure-code from s3 url
  api/src/lib/aws.ts
Labels: bug, javascript

#156 CPF-138 Add validation button group
  package.json
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.stories.tsx
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
  yarn.lock
Labels: enhancement, javascript, dependencies

#155 cpfValidation handler
  api/src/functions/cpfValidation/cpfValidation.scenarios.ts
  api/src/functions/cpfValidation/cpfValidation.test.ts
  api/src/functions/cpfValidation/cpfValidation.ts
  terraform/functions.tf
Labels: enhancement, javascript, terraform, infra

#164 CPF validation refactor + tests
  .gitattributes
  python/src/lib/workbook_validator.py
  python/src/schemas/latest/schema.py
  python/tests/conftest.py
  python/tests/data/sample_valid.xlsm
  python/tests/src/lib/test_workbook_validator.py
Labels: github

#140 Agency Workbook Upload - Validation Processing
  .gitattributes
  .github/release-drafter.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/publish-qa-results.yml
  .github/workflows/qa.yml
  .github/workflows/terraform-apply.yml
  .github/workflows/terraform-plan.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  docs/resolving-qa-failures.md
  python/build-lambda.bash
  python/poetry.lock
  python/pyproject.toml
  python/src/__init__.py
  python/src/functions/__init__.py
  python/src/functions/validate_workbook.py
  python/src/lib/__init__.py
  python/src/lib/logging.py
  python/src/lib/workbook_validator.py
  python/src/schemas/__init__.py
  python/src/schemas/latest/__init__.py
  python/src/schemas/latest/schema.py
  python/tests/__init__.py
  python/tests/conftest.py
  python/tests/data/sample_valid.xlsm
  python/tests/src/__init__.py
  python/tests/src/lib/__init__.py
  python/tests/src/lib/test_workbook_validator.py
  terraform/.terraform.lock.hcl
  terraform/functions.tf
  terraform/staging.tfvars
  terraform/variables.tf
  terraform/versions.tf
Labels: documentation, github, terraform, infra, dependencies

#165 Fix: Invalid Datadog layer ARN for Python lambdas
  terraform/functions.tf
Labels: bug, terraform, infra

#167 fix: duplicate suffix in notification configuration
  terraform/functions.tf
Labels: bug, terraform, infra

#168 fix: ensure cpfValidation lambda points to the python s3 object
  terraform/functions.tf
Labels: bug, terraform, infra

#169 Feature/CPF-159 Upload Details page
  web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
  web/src/components/Upload/Upload/Upload.stories.tsx
  web/src/components/Upload/Upload/Upload.tsx
  web/src/components/Upload/UploadCell/UploadCell.tsx
  web/src/components/Upload/UploadForm/UploadForm.tsx
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
  web/src/components/Upload/UploadValidationStatus/UploadValidationStatus.tsx
  web/src/components/Upload/Uploads/columns.tsx
  web/src/components/Upload/UploadsCell/UploadsCell.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript

#171 CPF-159 handle undefined EC Code in Upload Detail view
  web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
  web/src/components/Upload/Upload/Upload.stories.tsx
  web/src/components/Upload/Upload/Upload.tsx
  web/src/components/Upload/Uploads/columns.tsx
Labels: bug, javascript

#173 Ensure an UploadValidation is created during creation of an Upload
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  web/src/components/Upload/NewUpload/NewUpload.tsx
  web/src/components/Upload/UploadForm/UploadForm.tsx
Labels: javascript

#174 chore: refactor duplication in uploads test scenarios
  api/src/services/uploads/uploads.scenarios.ts
Labels: bug, javascript

#175 fix: relationship between users and organization
  api/src/lib/auth.ts
  web/src/components/Agency/AgencyForm/AgencyForm.tsx
  web/src/components/Upload/NewUpload/NewUpload.tsx
  web/src/components/User/User/User.tsx
  web/src/components/User/UserForm/UserForm.tsx
  web/src/pages/Agency/AgenciesPage/AgenciesPage.tsx
  web/src/pages/User/UsersPage/UsersPage.tsx
Labels: bug, javascript

#176 Fix upload form errors
  api/src/graphql/uploads.sdl.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  api/types/graphql.d.ts
  web/src/components/Upload/UploadForm/UploadForm.tsx
  web/types/graphql.d.ts
Labels: bug, javascript

#177 fix: incorrect orgID and removes duplicate method
  api/src/lib/aws.ts
  api/src/services/uploads/uploads.ts
Labels: bug, javascript

#178 try: removing multipart upload
  web/src/components/Upload/UploadForm/UploadForm.tsx
Labels: javascript

#179 Specify SSE header on S3 upload PUT request
  web/src/components/Upload/UploadForm/UploadForm.tsx
Labels: javascript

#180 Update graphql lambda permissions to allow uploads
  terraform/functions.tf
Labels: terraform, infra

#181 fix: re-add mistakenly removed function trigger
  terraform/functions.tf
Labels: bug, terraform, infra

#183 Expect temp file input to validate function
  python/src/lib/workbook_validator.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: bug, python

#185 Fix: 182 Avoid reading workbooks into memory before validation
  python/src/functions/validate_workbook.py
  python/src/lib/workbook_validator.py
  python/tests/conftest.py
  python/tests/src/lib/test_workbook_validator.py
Labels: bug, python

#186 fix: permissions for processValidationJSON function
  terraform/functions.tf
Labels: bug, terraform, infra

#187 Download file button/backend
  api/src/graphql/uploads.sdl.ts
  api/src/lib/aws.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
  api/types/graphql.d.ts
  web/src/components/Upload/Upload/Upload.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript

#191 add: graphql the ability to GET S3 objects
  terraform/functions.tf
Labels: terraform, infra

#193 Fix: JSON parsing issues in processValidationJson lambda function
  api/src/functions/processValidationJson/processValidationJson.test.ts
  api/src/functions/processValidationJson/processValidationJson.ts
  api/src/lib/aws.ts
Labels: bug, javascript

#195 fix: file-key string from s3
  api/src/functions/processValidationJson/processValidationJson.test.ts
  api/src/functions/processValidationJson/processValidationJson.ts
Labels: bug, javascript

#197 fix: add database credentials to processValidationJson function
  terraform/functions.tf
Labels: bug, terraform, infra

#198 fix: adds missing permissions for processValidationJson to access database
  terraform/functions.tf
Labels: bug, terraform, infra

#199 Set upload EC code
  api/src/functions/processValidationJson/processValidationJson.test.ts
  api/src/functions/processValidationJson/processValidationJson.ts
  python/src/functions/validate_workbook.py
  python/src/lib/workbook_validator.py
  python/tests/src/lib/test_workbook_validator.py
Labels: javascript, python

#202 Change cache path for deploy config
  terraform/web.tf
Labels: terraform, infra

#205 Navigate to individual upload page after submission
  web/src/components/Upload/NewUpload/NewUpload.tsx
  web/src/components/Upload/UploadForm/UploadForm.tsx
Labels: javascript

#206 Only attempt to save expenditure category if there is a project use code
  api/src/functions/processValidationJson/processValidationJson.test.ts
  api/src/functions/processValidationJson/processValidationJson.ts
Labels: javascript

#209 Update frontend components to use updated schema
  web/src/components/Upload/Upload/Upload.stories.tsx
  web/src/components/Upload/Upload/Upload.tsx
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.stories.tsx
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
Labels: javascript

#211 fix: issue with python lambda downloading workbooks
  python/src/functions/validate_workbook.py
Labels: bug, python

#210 CPF-119 Passage API - getCurrentUser()
  api/src/lib/auth.test.ts
  api/src/lib/auth.ts
  web/src/pages/LoginPage/LoginPage.test.tsx
  web/types/graphql.d.ts
Labels: enhancement, javascript

#212 fix: more url corrections across lambdas
  api/src/functions/processValidationJson/processValidationJson.ts
  python/src/functions/validate_workbook.py
Labels: bug, javascript, python

#216 CPF-214 Scope uploads by user role
  api/src/services/uploads/uploads.scenarios.ts
  api/src/services/uploads/uploads.test.ts
  api/src/services/uploads/uploads.ts
Labels: enhancement, javascript

#215 Update python errors schema
  python/src/functions/validate_workbook.py
  python/src/lib/workbook_validator.py
  python/src/schemas/latest/schema.py
  python/tests/src/lib/test_workbook_validator.py
Labels: python

#219 CPF-213 Hide features 2024-05-13 milestone
  web/src/Routes.tsx
  web/src/components/Navigation/Navigation.tsx
  web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
  web/src/pages/Upload/UploadsPage/UploadsPage.tsx
Labels: enhancement, javascript

#218 chore: add version support for latest input template
  python/src/schemas/latest/schema.py
Labels: python

#220 fix: Adds support for 2024-04-01 and removes incorrect 2024-04-04
  python/src/schemas/latest/schema.py
Labels: bug, python

#224 Add JSON preferences field to organization table
  api/db/migrations/20240425200607_add_preferences_to_organization/migration.sql
  api/db/schema.prisma
  api/src/graphql/organizations.sdl.ts
  api/types/graphql.d.ts
  web/types/graphql.d.ts
Labels: javascript, database

#227 Add production deployment pipeline
  .github/release-drafter.yml
  .github/workflows/aws-auth.yml
  .github/workflows/deploy-production.yml
Labels: enhancement, github, infra

#229 fix: ensure users can only upload .xlsm files
  web/src/components/Upload/UploadForm/UploadForm.tsx
Labels: bug, javascript

#230 Add script tag for deploy-config and make things work locally
  web/config/webpack.config.js
  web/public/deploy-config.js
  web/src/index.html
  web/vite.config.ts
Labels: javascript

#226 Validate all sheets before returning
  python/src/lib/workbook_validator.py
  python/tests/src/lib/test_workbook_validator.py
Labels: bug, python

#234 chore: enable local auth in staging
  terraform/functions.tf
  terraform/staging.tfvars
  terraform/variables.tf
Labels: terraform, infra

#235 fix: makes config name lowercase to match terraform
  web/src/auth.ts
  web/src/pages/LoginPage/LoginPage.tsx
Labels: bug, javascript

#236 fix: ability to dump validation errors into json without type-errors
  python/src/lib/workbook_validator.py
  python/src/schemas/latest/schema.py
  python/tests/src/lib/test_workbook_validator.py
  web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.tsx
Labels: bug, javascript, python
